apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: soldev-jenkins
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jefff@jfrog.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          clouddns:
            # The ID of the GCP project
            project: soldev-dev
            # This is the secret used to access the service account
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json