apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: soldev-jenkins
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jefff@jfrog.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx