apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: jenkins-openshiftk8s-com
  namespace: soldev-jenkins
spec:
  secretName: jenkins-openshiftk8s-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: jenkins.openshiftk8s.com
  dnsNames:
    - jenkins.openshiftk8s.com