fullnameOverride: soldev-jenkins
namespaceOverride: soldev-jenkins
persistence:
  existingClaim: soldev-jenkins-volume
master:
  resources:
    limits: {memory: 1G}
  serviceType: LoadBalancer
  ingress:
    enabled: true
    labels: {app: soldev-jenkins}
    path: "/"
    hostName: soldev-ci.104.197.237.136.xip.io
    annotations: {kubernetes.io/ingress.class: "nginx",
                  cert-manager.io/issuer: "selfsigned-issuer"}
    tls:
      - hosts:
        - soldev-ci.104.197.237.136.xip.io
        secretName: soldev-ci-104-197-237-136-xip-io-tls
  installPlugins:
    - kubernetes:1.24.1
    - workflow-job:2.36
    - workflow-aggregator:2.6
    - credentials-binding:1.21
    - git:4.2.0
    - artifactory:3.6.1